food=input("Name a food: ")
plant=input("Name a plant: ")
cooking=input("Name a cooking method: ")
burned=input("Name a burnt food: ")
item=input("Name a DIY item: ")
print()
print("MENU")
print(cooking,food ,"with",burned,plant ,"on a bed of",item)
